<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

## *Data Science Unit 4 Sprint 2*

# Sprint Challenge - Neural Network Foundations

Table of Problems

1. [Defining Neural Networks](#Q1)
2. [Perceptron on XOR Gates](#Q2)
3. [Multilayer Perceptron](#Q3)
4. [Keras MMP](#Q4)

<a id="Q1"></a>
## 1. Define the following terms:

- **Neuron:** In biology, a neuron takes in an input through it's dendrites, leading to action potential, if the signal is huge enough, it is passed down its axon to the next cell body. In computer science, neurons take in an input, assign some weight to it, perform computation and activation and gives us an output
- **Input Layer:** Input is the features we give the neuron network. Typically we have one input node for each feature/column that we give our neuron
- **Hidden Layer:** This is invisible to us and is where the neuron performs computation, makes connection between features and and perform their calculation. We do not interact with hidden layers directly. The most simple neural network has only one hidden layer.
- **Output Layer:** This is what gives us the resuls of the computation from the hidden layers. We typically use activation functions to change the output to a format that makees sense for our problem. Different types of problems have different types of activation functions for the output layer
- **Activation:** In neural networks, activation functions decide on how much signal to pass onto to next layer. For a simple classification problem, we use a sigmoid function but for multi-class we might use something as a softmax function which gives each output probabilities, which add up to 1. 
- **Backpropagation:** Backpropagation is a method where the weights of the inputs are updated after completion of one cycle of going through the model. This way we can see which inputs are giving the most desirable results when we get to the output layer and in the next cycle, more weight is assigned to them to train the model. 


## 2. Perceptron on ANDGates <a id="Q3=2"></a>

Create a perceptron class that can model the behavior of an AND gate. You can use the following table as your training data:

|x1	|x2|x3|	y|
|---|---|---|---|
1|	1|	1|	1|
1|	0|	1|	0|
0|	1|	1|	0|
0|	0|	1|	0|

In [126]:
import numpy as np
import pandas as pd


In [127]:
inputs = np.array([[1,1,1,1], [0,1,0,1], [0,1,1,0], [0,1,0,0]])

ground_truth = np.array([[1], [0], [0], [0]])



In [128]:
def sigmoid(x): #normalizes the data by changing it between 0 to 1
    return 1 / (1+np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1-sx)


In [129]:
weights = 2 * np.random.random((4,1)) - 1

for iteration in range(1000):
    
    #weighted_sum of inputs/weights
    weighted_sum = np.dot(inputs, weights)
    #activate the weighted_sum function
    activated_output = sigmoid(weighted_sum)
    #calculate an error
    error = ground_truth - activated_output
    #adjustments
    adjustments = error * sigmoid_derivative(activated_output)
    weights+=np.dot(inputs.T, adjustments)
    

In [130]:
print("weights after training:")
print(weights)

print("Output after training:")
print(activated_output) #yay, it is correctly predicting it. need to have a test set though, will come back

weights after training:
[[ 7.99318876]
 [-7.14252174]
 [ 1.95101647]
 [ 1.95387266]]
Output after training:
[[9.91461191e-01]
 [5.55403745e-03]
 [5.53826268e-03]
 [7.91146178e-04]]


In [135]:
nn = NeuralNetwork()

print("Layer 1 weights: \n", nn.weights1)
print("Layer 2 weights: \n", nn.weights2)

Layer 1 weights: 
 [[-0.49452034  2.02356098 -1.02358866  0.63913727]
 [-1.21196218  0.4217074   1.08821312  0.78110355]
 [-1.51593775 -0.1619868  -1.67060114  1.53969052]
 [-0.80653933 -0.27017499 -0.24941648 -0.48115543]
 [-0.20382417  0.41071841 -1.24551494  0.66723513]
 [ 0.72815225  1.39675411  1.57214174 -0.75844215]
 [-0.77546331 -0.62880606 -0.40647842 -0.03186804]
 [-0.48256036 -0.18402828 -1.23187471  1.33843267]
 [-1.17142164 -1.40147136  0.24611614 -0.21440805]
 [-0.6899713  -0.28596439  0.0815114  -0.79805832]
 [-1.5616287   1.46402632 -0.14427755 -0.35140554]
 [-1.39220024  0.41067098 -0.44839561 -1.09939544]
 [-0.11747193  1.28248974  1.07314652 -0.29602579]]
Layer 2 weights: 
 [[0.75330291 0.75198832]
 [0.55802997 0.86601481]
 [0.57513926 0.10895715]
 [0.15623399 0.05865977]]


## 3. Multilayer Perceptron <a id="Q3"></a>

Implement a Neural Network Multilayer Perceptron class that uses backpropagation to update the network's weights.
Your network must have one hidden layer.
You do not have to update weights via gradient descent. You can use something like the derivative of the sigmoid function to update weights.
Train your model on the Heart Disease dataset from UCI:



In [240]:
heart = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/heart.csv')

heart.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [241]:
heart.describe()


age         sex          cp    trestbps        chol         fbs  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean    54.366337    0.683168    0.966997  131.623762  246.264026    0.148515   
std      9.082101    0.466011    1.032052   17.538143   51.830751    0.356198   
min     29.000000    0.000000    0.000000   94.000000  126.000000    0.000000   
25%     47.500000    0.000000    0.000000  120.000000  211.000000    0.000000   
50%     55.000000    1.000000    1.000000  130.000000  240.000000    0.000000   
75%     61.000000    1.000000    2.000000  140.000000  274.500000    0.000000   
max     77.000000    1.000000    3.000000  200.000000  564.000000    1.000000   

          restecg     thalach       exang     oldpeak       slope          ca  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean     0.528053  149.646865    0.326733    1.039604    1.399340    0.729373   
std      0.525860   22.905161    0.469794    1.161075    0.616226    1.022606   
min      0.000000   71.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000  133.500000    0.000000    0.000000    1.000000    0.000000   
50%      1.000000  153.000000    0.000000    0.800000    1.000000    0.000000   
75%      1.000000  166.000000    1.000000    1.600000    2.000000    1.000000   
max      2.000000  202.000000    1.000000    6.200000    2.000000    4.000000   

             thal      target  
count  303.000000  303.000000  
mean     2.313531    0.544554  
std      0.612277    0.498835  
min      0.000000    0.000000  
25%      2.000000    0.000000  
50%      2.000000    1.000000  
75%      3.000000    1.000000  
max      3.000000    1.000000

In [242]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [217]:
heart['target'] = heart['target'].astype(float)

In [218]:
y[:10]

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]], dtype=int64)

In [219]:
X[:10]

array([[ 63. ,   1. ,   3. , 145. , 233. ,   1. ,   0. , 150. ,   0. ,
          2.3,   0. ,   0. ,   1. ],
       [ 37. ,   1. ,   2. , 130. , 250. ,   0. ,   1. , 187. ,   0. ,
          3.5,   0. ,   0. ,   2. ],
       [ 41. ,   0. ,   1. , 130. , 204. ,   0. ,   0. , 172. ,   0. ,
          1.4,   2. ,   0. ,   2. ],
       [ 56. ,   1. ,   1. , 120. , 236. ,   0. ,   1. , 178. ,   0. ,
          0.8,   2. ,   0. ,   2. ],
       [ 57. ,   0. ,   0. , 120. , 354. ,   0. ,   1. , 163. ,   1. ,
          0.6,   2. ,   0. ,   2. ],
       [ 57. ,   1. ,   0. , 140. , 192. ,   0. ,   1. , 148. ,   0. ,
          0.4,   1. ,   0. ,   1. ],
       [ 56. ,   0. ,   1. , 140. , 294. ,   0. ,   0. , 153. ,   0. ,
          1.3,   1. ,   0. ,   2. ],
       [ 44. ,   1. ,   1. , 120. , 263. ,   0. ,   1. , 173. ,   0. ,
          0. ,   2. ,   0. ,   3. ],
       [ 52. ,   1. ,   2. , 172. , 199. ,   1. ,   1. , 162. ,   0. ,
          0.5,   2. ,   0. ,   3. ],
       [ 57. ,   1. ,   2. ,

In [220]:
class NeuralNetwork:
    def __init__(self):
        # Set up Architecture
        self.inputs = 13
        self.hiddenNodes = 13
        self.outputNodes = 1

        #Initial weights
        self.weights1 = np.random.randn(self.inputs, self.hiddenNodes) #2x3
        self.weights2 = np.random.rand(self.hiddenNodes, self.outputNodes) #3x1

    def sigmoid(self, s):
        return 1 / (1+np.exp(-s))

    def sigmoidPrime(self, s):
        return s * (1 - s)

    def feed_forward(self, X):
        """
        Calculate the NN inference using feed forward.
        """

        #Weighted sume of inputs and hidden layer
        self.hidden_sum = np.dot(X, self.weights1)

        #Acivations of weighted sum
        self.activated_hidden = self.sigmoid(self.hidden_sum)

        # Weight sum between hidden and output
        self.output_sum = np.dot(self.activated_hidden, self.weights2)

        #Final activation of output
        self.activated_output = self.sigmoid(self.output_sum)

        return self.activated_output

    def backward(self, X, y, o):
        """
        Backward propagate through the network
        """
        self.o_error = y - o #error in output
        self.o_delta = self.o_error * self.sigmoidPrime(o) # apply derivative of sigmoid to error

        self.z2_error = self.o_delta.dot(self.weights2.T) # z2 error: how much our hidden layer weights were off
        self.z2_delta = self.z2_error*self.sigmoidPrime(self.activated_hidden)

        self.weights1 += X.T.dot(self.z2_delta) #Adjust first set (input => hidden) weights
        self.weights2 += self.activated_hidden.T.dot(self.o_delta) #adjust second set (hidden => output) weights

    def train(self, X, y):
        self.X = X
        self.y = y
        o = self.feed_forward(X)
        self.backward(X, y, o)

In [221]:
nn = NeuralNetwork()

for i in range(100):
    nn.train(X, y)

In [223]:
print('output: \n', str(nn.feed_forward(X)))
#print("Loss func: \n", str(np.mean(np.square(target - nn.feed_forward(X)))))

output: 
 [[1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]
 [1.12884872e-07]


Implement a Neural Network Multilayer Perceptron class that uses backpropagation to update the network's weights. Your network must have one hidden layer. You do not have to update weights via gradient descent. You can use something like the derivative of the sigmoid function to update weights. Train your model on the Heart Disease dataset from UCI:

## 4. Keras MMP <a id="Q4"></a>

Implement a Multilayer Perceptron architecture of your choosing using the Keras library. Train your model and report its baseline accuracy. Then hyperparameter tune at least two parameters and report your model's accuracy.
Use the Heart Disease Dataset (binary classification)
Use an appropriate loss function for a binary classification task
Use an appropriate activation function on the final layer of your network.
Train your model using verbose output for ease of grading.
Use GridSearchCV to hyperparameter tune your model. (for at least two hyperparameters)
When hyperparameter tuning, show you work by adding code cells for each new experiment.
Report the accuracy for each combination of hyperparameters as you test them so that we can easily see which resulted in the highest accuracy.
You must hyperparameter tune at least 5 parameters in order to get a 3 on this section.

In [164]:
import keras
from keras.models import Sequential
from keras.layers import Dense
import pandas as pd
import numpy

In [247]:
# Import data again, arrays errors
import pandas as pd
from scipy import optimize

df = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/heart.csv')

X = df.drop(columns='target').values
y = df[['target']].values
print(df.shape)
df.head()

(303, 14)


age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [248]:
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size=0.2, 
                                                    random_state=42)

In [229]:
import numpy
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier

In [249]:
def create_model():
# create model
    model = Sequential()
    # input + first hidden layer
    model.add(Dense(12, input_dim=13, activation='relu'))
    # second hidden layer
    model.add(Dense(8, input_dim=13, activation = 'relu'))
    # output layer
    model.add(Dense(1, activation='sigmoid'))
    # Compile model
    model.compile(loss='binary_crossentropy',
                  optimizer='adam',
                  metrics=['accuracy'])
    return model


In [250]:
baseline = model.fit(X_train, y_train,
                          epochs=100,
                          batch_size=64,
                          validation_data=(X_test, y_test),
                          verbose=0)
scores = model.evaluate(X_test, y_test)
print('Neural Network ACC: ', scores[1])

61/61 [==============================] - 0s 114us/step
Neural Network ACC:  0.4754098316685098


# So I have got the baseline here which is pretty low, let's try with different epochs and batch_sizes

In [ ]:
# create model
model = KerasClassifier(build_fn=create_model, verbose=1)

# define the grid search parameters
batch_size = [10, 20, 40, 60, 80, 100]
param_grid = dict(batch_size=batch_size, epochs=epochs)

# define the grid search parameters
param_grid = {'batch_size': [10, 20, 40, 60, 80, 100],
              'epochs': [20, 40, 60, 80, 100]}

# Create Grid Search
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1)
grid_result = grid.fit(X, y)

# Report Results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}") 

C:\Users\Billi\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)


Epoch 1/20
202/202 [==============================] - 4s 19ms/step - loss: 2.1065 - acc: 0.4208
Epoch 2/20
202/202 [==============================] - 0s 331us/step - loss: 1.3152 - acc: 0.5990
Epoch 3/20
202/202 [==============================] - 0s 321us/step - loss: 1.0028 - acc: 0.5941
Epoch 4/20
202/202 [==============================] - 0s 390us/step - loss: 0.9083 - acc: 0.6089
Epoch 5/20
202/202 [==============================] - 0s 336us/step - loss: 0.8257 - acc: 0.6089
Epoch 6/20
202/202 [==============================] - 0s 331us/step - loss: 0.7916 - acc: 0.6040
Epoch 7/20
202/202 [==============================] - 0s 316us/step - loss: 0.7483 - acc: 0.6436
Epoch 8/20
202/202 [==============================] - 0s 336us/step - loss: 0.6992 - acc: 0.6535
Epoch 9/20
202/202 [==============================] - 0s 321us/step - loss: 0.6886 - acc: 0.6386
Epoch 10/20
202/202 [==============================] - 0s 331us/step - loss: 0.6467 - acc: 0.6931
Epoch 11/20
202/202 [=========

### Hyperparameter Tuning ###


In [172]:
# define the grid search parameters
param_grid = {'batch_size': [60, 80],
              'epochs': [20, 40, 60]}

# Create Grid Search
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1)
grid_result = grid.fit(X, y)

# Report Results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}")

Epoch 1/20
202/202 [==============================] - 3s 14ms/step - loss: 0.7683 - acc: 0.3762
Epoch 2/20
202/202 [==============================] - 0s 94us/step - loss: 0.7319 - acc: 0.4208
Epoch 3/20
202/202 [==============================] - 0s 89us/step - loss: 0.6979 - acc: 0.5149
Epoch 4/20
202/202 [==============================] - 0s 79us/step - loss: 0.6692 - acc: 0.5693
Epoch 5/20
202/202 [==============================] - 0s 69us/step - loss: 0.6429 - acc: 0.6386
Epoch 6/20
202/202 [==============================] - 0s 79us/step - loss: 0.6189 - acc: 0.6733
Epoch 7/20
202/202 [==============================] - 0s 79us/step - loss: 0.5994 - acc: 0.7030
Epoch 8/20
202/202 [==============================] - 0s 74us/step - loss: 0.5795 - acc: 0.7277
Epoch 9/20
202/202 [==============================] - 0s 84us/step - loss: 0.5635 - acc: 0.7277
Epoch 10/20
202/202 [==============================] - 0s 79us/step - loss: 0.5498 - acc: 0.7178
Epoch 11/20
202/202 [==================

In [ ]:
# that looks a little better!